version: 1
formatters:
  simple:
    format: '{levelname} {name} {message}'
    style: '{'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: 'build/lkpy.log'
    encoding: utf8
    mode: 'a'
loggers:
  exp:
    level: INFO
    handlers: [console,file]
  lenskit:
    level: DEBUG
    handlers: [console,file]
  invoke:
    level: INFO
root:
  level: INFO
  handler: [console]